name: Create EXE and Add To Release
on:
  release:
    types: [published]

jobs:
  releaseTxz:
    name: Create Txz and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - name: Run PyInstaller to Create EXE from src
        id: pyinstaller
        run: |
          python -m venv .
          python -m pip install -r requirements.txt
          pyinstaller AsanaExportTool.spec
          cp dist/AsanaExportTool.exe AsanaExportTool-${{ github.event.release.tag_name }}.exe
      - name: Release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            AsanaExportTool-${{ github.event.release.tag_name }}.exe
