name: Create EXE and Add To Release
on:
  release:
    types: [published]

jobs:
  LinuxRelease:
    name: Create Linux Release
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.event.release.tag_name }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Run PyInstaller to Create Python Binary
        id: pyinstaller-linux
        run: |
          python --version
          python -m venv .
          python -m pip install -r requirements.txt
          pyinstaller AsanaExportTool.spec
          ls -la
          ls -la ./dist
          zip ./AsanaExportTool-${{ env.TAG }}.txz ./dist/AsanaExportTool
      - name: Release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./AsanaExportTool-${{ env.TAG }}.txz
  WindowsRelease:
    name: Create Windows Release
    runs-on: windows-latest
    env:
      TAG: ${{ github.event.release.tag_name }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Run PyInstaller to Create Windows EXE
        id: pyinstaller-windows
        run: |
          python --version
          python -m venv .
          python -m pip install -r requirements.txt
          pyinstaller AsanaExportTool.spec
          ls
          ls .\\dist
          copy .\\dist\\AsanaExportTool.exe .\\AsanaExportTool-${{ env.TAG }}.exe
      - name: Release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./AsanaExportTool-${{ env.TAG }}.exe
